[project]
name = "net-worth-tracker"
version = "0.1.0"
description = "Net Worth Tracker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
